### ISSUE TITLE
Bump dawn version

### ISSUE THREAD

**Issue by Vertexwahn** [beaufortfrancois/webgpu-cross-platform-app#1]
WebGPU using Emscripten works on older hardware for me (using Chrome) - but not with Dawn. Maybe we should update the referenced dawn version - maybe this support older hardware better?

**Comment by kainino0x** [comment]
The version of dawn is not _that_ old yet, I don't suspect we've recently done anything to make it work on older hardware, but it's possible. Have you tried building against a newer dawn revision?

Could you share more info about the system you're running on and what goes wrong when you try to run it? (and any error logs)

**Comment by beaufortfrancois** [comment]
@Vertexwahn Did you have a chance to try with a newer dawn version?
