### ISSUE TITLE
Web build not working, no errors

### ISSUE THREAD

**Issue by lesleyrs** [beaufortfrancois/webgpu-cross-platform-app#6]
I'm on google chrome with webgpu enabled, the dawn build works correctly but nothing happens in the emscripten one when running a web server.

No console output and blank screen, just the emscripten html page. Did it break for everyone?

**Comment by beaufortfrancois** [comment]
Does it work for you when running it natively?
Can you share logs maybe when running https://github.com/beaufortfrancois/webgpu-cross-platform-app/blob/main/README.md#web-build steps?

**Comment by lesleyrs** [comment]
Yes native works, there are no logs in console when running web build. It just has a glitchy blank canvas where the triangle is supposed to be.

**Comment by beaufortfrancois** [comment]
As I didn't build this app on Windows yet, I may be missing some obvious stuff.
